version: "3"

services:
  database:
    image: mysql
    container_name: dote_database
    environment:
      - MYSQL_DATABASE=dote_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/revision/docker_spring/database/dote_db/:/var/lib/mysql
    networks:
      - test_network_02
    restart: unless-stopped

  application:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - database
      - redis
    container_name: dote_application
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/dote_db?useSSL=false&serverTimezone=UTC&LegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - test_network_02

networks:
  test_network_02: